### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by neofright**
A few changes to hopefully improve readability.

### CODE REVIEW

**Comment by kurokobo** [comment]
@neofright 
Huge thanks for your PR! This is very helpful for me since I don't have enough confident about my English 😃
I'll review on this!

**Comment by neofright** [comment]
Thank you for very much for this repo. It has made the process of getting AWX running understandable as I have no prior experience with K8s!

**Comment by kurokobo** [comment]
@neofright 
Thanks for all the continuous work! I just changed this to draft PR, so can you change it back or let me know when you're done working on this?

**Comment by neofright** [comment]
@kurokobo 
Apologies for the changing WIP commits.

Yes, please leave it as a draft and I will mark it for review when I'm done. I'm basically making the edits as I read the repo!

**Comment by neofright** [comment]
I've squashed and tidied up the commits a little. I won't commit any other changes to this branch until this PR is merged.

**Comment by kurokobo** [comment]
@neofright 
Merged, thanks again for all the work!

**Pull request merged**
